### PR TITLE
Use tags without "v" prefix

### PR DESCRIPTION
**Pull request by rail**
This repo and other scriptworker repos use tags without the "v" prefix.
It would be better to use the same approach here as well.

### CODE REVIEW

**Comment by mitchhentges** [comment]
I think it's awesome to make our repositories consistent, but should we centralize on removing the `v`, or adding the `v`?

According to GitHub, the wider standard is to keep the `v` in the tag name:
Screenshot from 2019-07-03 10-19-45
(that image is from the GitHub "draft a release" page)

**Comment by escapewindow** [comment]
Blue?

**Comment by rail** [comment]
I'm open to use "v", but better to keep the tagging schema unified.

**Comment by rail** [comment]
> Blue?

[Pink](http://bikeshed.com/)!!! :D

**Pull request merged**
