### PR TITLE
Use Docker-in-Docker

### PR DESCRIPTION
**Pull request by rail**
This replaces the privileged mode approach and uses docker-in-docker to build the image.

### CODE REVIEW

**Comment by rail** [comment]
I thought about using taskgraph, but then I realized that it uses its own directory hierarchy, so the docker context is not the root directory, where I should copy the files from... Maybe there is a work around or a known way to change the context?

**Comment by tomprince** [comment]
[This](https://hg.mozilla.org/ci/taskgraph/file/tip/taskcluster/docker/decision-user/Dockerfile#l5) is how taskgraph itself handles doing this.

**Comment by rail** [comment]
> [This](https://hg.mozilla.org/ci/taskgraph/file/tip/taskcluster/docker/decision-user/Dockerfile#l5) is how taskgraph itself handles doing this.

Thanks, GTK. 

One thing that concerns me about this approach is that you cannot use `docker build` for these Dockerfiles, so there is no good way to test the changes locally without a PR/push.

Also I would need to solve the publishing step somehow, since taskgraph doesn't support pushing images.

BTW, is there any objections against the current approach? It will unblock other scriptworker migration to GCP.

**Comment by tomprince** [comment]
> One thing that concerns me about this approach is that you cannot use `docker build` for these Dockerfiles, so there is no good way to test the changes locally without a PR/push.

`taskgraph build-image <task-name>`
 
> Also I would need to solve the publishing step somehow, since taskgraph doesn't support pushing images.

I think what you have here would work (assuming taskboot can handle zstd. That said, we should reach out to cloud-ops and see if they can pull from taskcluster directly.

> BTW, is there any objections against the current approach? It will unblock other scriptworker migration to GCP.

No.

**Comment by rail** [comment]
I'm going to proceed with this solution for now. I plan to revisit this approach and use taskgraph ASAP, just want to move forward. I may bother you you with more questions. :)

**Comment by rail** [comment]
Pushing doesn't work as expected due to the ancient image format that dind generates. :angry:

**Pull request merged**
